from enum import Enum

class CMD(Enum): # lab 1
    PING = 0
    SEND_TWO_INTS = 1
    SEND_THREE_FLOATS = 2
    ECHO = 3
    DANCE = 4
    SET_VEL = 5
    GET_TIME_MILLIS = 6
    GET_CURRRENT_TIME_LOOP = 7
    STORE_TIME_STAMP = 8
    SEND_TIME_DATA = 9
    STORE_TIME_TEMP_STAMP = 10
    GET_TEMP_READINGS = 11

class CMD_lab2(Enum):
    PING = 0
    ECHO = 1
    GET_TIME_MILLIS = 2
    GET_CURRRENT_TIME_LOOP = 3
    STORE_TIME_STAMP = 4
    SEND_TIME_DATA = 5
    STORE_TIME_TEMP_STAMP = 6
    GET_TEMP_READINGS = 7
    GET_ACCEL_DATA = 8
    GET_ACCEL_NOISE = 9
    GET_GYRO_DATA = 10
    GET_COMPL_DATA = 11

class CMD_lab3(Enum):
    GET_2TOF_DATA = 0
    GET_IMU_DATA = 1
    GET_2TOF_IMU_TIME_DATA = 2


class CMD_lab5(Enum):
    START_LINEAR_PID = 0
    STOP_LINEAR_PID = 1
    SEND_LINEAR_PID_DATA = 2

class CMD_lab6(Enum):
    # Lab 5 - linear pid
    START_LINEAR_PID = 0
    STOP_LINEAR_PID = 1
    SEND_LINEAR_PID_DATA = 2
    # Lab 6 - orientation pid
    START_ORIENTATION_PID = 3
    STOP_ORIENTATION_PID = 4
    SEND_ORIENTATION_PID_DATA = 5
    SET_ORIENTATION_SETPOINT = 6
    RESET_YAW = 7
    
    
    